# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import QCoreApplication, QMetaObject, QRect, Qt
from PySide6.QtGui import QFont
from PySide6.QtWidgets import (QCheckBox, QComboBox, QDateEdit, QDoubleSpinBox,
                               QLabel, QLineEdit, QProgressBar, QPushButton,
                               QSlider, QSpinBox, QTextBrowser)


class SampleUiLayout(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(430, 394)
        self.submit_button = QPushButton(Form)
        self.submit_button.setObjectName(u"submit_button")
        self.submit_button.setGeometry(QRect(270, 300, 141, 31))
        self.name_label = QLabel(Form)
        self.name_label.setObjectName(u"name_label")
        self.name_label.setGeometry(QRect(20, 50, 51, 21))
        self.user_name = QLineEdit(Form)
        self.user_name.setObjectName(u"user_name")
        self.user_name.setGeometry(QRect(90, 50, 113, 21))
        self.nationality = QComboBox(Form)
        self.nationality.setObjectName(u"nationality")
        self.nationality.setGeometry(QRect(90, 90, 111, 22))
        self.nationality_label = QLabel(Form)
        self.nationality_label.setObjectName(u"nationality_label")
        self.nationality_label.setGeometry(QRect(20, 90, 61, 21))
        self.name_label_2 = QLabel(Form)
        self.name_label_2.setObjectName(u"name_label_2")
        self.name_label_2.setGeometry(QRect(220, 50, 71, 21))
        self.place_of_birth = QLineEdit(Form)
        self.place_of_birth.setObjectName(u"place_of_birth")
        self.place_of_birth.setGeometry(QRect(300, 50, 113, 21))
        self.name_label_3 = QLabel(Form)
        self.name_label_3.setObjectName(u"name_label_3")
        self.name_label_3.setGeometry(QRect(220, 90, 71, 21))
        self.date_of_birth = QDateEdit(Form)
        self.date_of_birth.setObjectName(u"date_of_birth")
        self.date_of_birth.setGeometry(QRect(300, 90, 111, 22))
        self.employed = QCheckBox(Form)
        self.employed.setObjectName(u"employed")
        self.employed.setGeometry(QRect(20, 130, 71, 31))
        self.married = QCheckBox(Form)
        self.married.setObjectName(u"married")
        self.married.setGeometry(QRect(120, 130, 71, 31))
        self.disabled = QCheckBox(Form)
        self.disabled.setObjectName(u"disabled")
        self.disabled.setGeometry(QRect(220, 130, 71, 31))
        self.drivers_license = QCheckBox(Form)
        self.drivers_license.setObjectName(u"drivers_license")
        self.drivers_license.setGeometry(QRect(310, 130, 91, 31))
        self.info_label = QLabel(Form)
        self.info_label.setObjectName(u"info_label")
        self.info_label.setGeometry(QRect(10, 0, 421, 41))
        font = QFont()
        font.setPointSize(25)
        self.info_label.setFont(font)
        self.info_label.setAlignment(Qt.AlignCenter)
        self.kids = QSpinBox(Form)
        self.kids.setObjectName(u"kids")
        self.kids.setGeometry(QRect(50, 180, 51, 22))
        self.name_label_4 = QLabel(Form)
        self.name_label_4.setObjectName(u"name_label_4")
        self.name_label_4.setGeometry(QRect(10, 180, 51, 21))
        self.name_label_5 = QLabel(Form)
        self.name_label_5.setObjectName(u"name_label_5")
        self.name_label_5.setGeometry(QRect(120, 180, 91, 21))
        self.school_average = QDoubleSpinBox(Form)
        self.school_average.setObjectName(u"school_average")
        self.school_average.setGeometry(QRect(210, 180, 62, 22))
        self.happiness = QSlider(Form)
        self.happiness.setObjectName(u"happiness")
        self.happiness.setGeometry(QRect(80, 230, 160, 22))
        self.happiness.setMaximum(10)
        self.happiness.setPageStep(1)
        self.happiness.setValue(10)
        self.happiness.setSliderPosition(10)
        self.happiness.setTracking(True)
        self.happiness.setOrientation(Qt.Horizontal)
        self.happiness.setTickPosition(QSlider.TicksBelow)
        self.happiness.setTickInterval(0)
        self.name_label_6 = QLabel(Form)
        self.name_label_6.setObjectName(u"name_label_6")
        self.name_label_6.setGeometry(QRect(10, 230, 61, 21))
        self.name_label_7 = QLabel(Form)
        self.name_label_7.setObjectName(u"name_label_7")
        self.name_label_7.setGeometry(QRect(230, 250, 41, 21))
        self.name_label_8 = QLabel(Form)
        self.name_label_8.setObjectName(u"name_label_8")
        self.name_label_8.setGeometry(QRect(80, 250, 41, 21))
        self.reason_of_application = QTextBrowser(Form)
        self.reason_of_application.setObjectName(u"reason_of_application")
        self.reason_of_application.setGeometry(QRect(10, 300, 251, 91))
        self.name_label_9 = QLabel(Form)
        self.name_label_9.setObjectName(u"name_label_9")
        self.name_label_9.setGeometry(QRect(10, 280, 111, 21))
        self.submit_progress = QProgressBar(Form)
        self.submit_progress.setObjectName(u"submit_progress")
        self.submit_progress.setGeometry(QRect(280, 350, 141, 23))
        self.submit_progress.setValue(0)
        self.submit_progress.setInvertedAppearance(False)
        self.submit_progress.setTextDirection(QProgressBar.TopToBottom)
        self.submit_button.raise_()
        self.name_label.raise_()
        self.user_name.raise_()
        self.nationality.raise_()
        self.nationality_label.raise_()
        self.name_label_2.raise_()
        self.place_of_birth.raise_()
        self.name_label_3.raise_()
        self.date_of_birth.raise_()
        self.employed.raise_()
        self.married.raise_()
        self.disabled.raise_()
        self.drivers_license.raise_()
        self.info_label.raise_()
        self.kids.raise_()
        self.name_label_4.raise_()
        self.name_label_5.raise_()
        self.school_average.raise_()
        self.name_label_6.raise_()
        self.name_label_7.raise_()
        self.name_label_8.raise_()
        self.happiness.raise_()
        self.reason_of_application.raise_()
        self.name_label_9.raise_()
        self.submit_progress.raise_()

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.submit_button.setText(QCoreApplication.translate("Form", u"Submit", None))
        self.name_label.setText(QCoreApplication.translate("Form", u"Name:", None))
        self.nationality_label.setText(QCoreApplication.translate("Form", u"Nationality:", None))
        self.name_label_2.setText(QCoreApplication.translate("Form", u"Place of birth:", None))
        self.place_of_birth.setText("")
        self.name_label_3.setText(QCoreApplication.translate("Form", u"Date of birth:", None))
        self.employed.setText(QCoreApplication.translate("Form", u"Employed", None))
        self.married.setText(QCoreApplication.translate("Form", u"Married", None))
        self.disabled.setText(QCoreApplication.translate("Form", u"Disabled", None))
        self.drivers_license.setText(QCoreApplication.translate("Form", u"Drivers license", None))
        self.info_label.setText(QCoreApplication.translate("Form", u"Information", None))
        self.name_label_4.setText(QCoreApplication.translate("Form", u"Kids", None))
        self.name_label_5.setText(QCoreApplication.translate("Form", u"School average:", None))
        self.name_label_6.setText(QCoreApplication.translate("Form", u"Happiness:", None))
        self.name_label_7.setText(QCoreApplication.translate("Form", u"Happy", None))
        self.name_label_8.setText(QCoreApplication.translate("Form", u"Sadge", None))
        self.name_label_9.setText(QCoreApplication.translate("Form", u"Reason of application:", None))
    # retranslateUi

